@baseurl = http://localhost:5027
@accept = application/json

POST {{baseurl}}/api/Auth/Login
Content-Type: application/json
Accept: {{accept}}
{
  "Email": "BobbyB@gmail.com",
  "Password": "TestPassword123!"
}